#if UNITY_EDITOR
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

/// <summary>
/// Editor validation for the Stage01 scene generated by Stage01MapBuilder.
/// Run this on the Unity-equipped machine after building the Gameplay scene.
/// </summary>
public static class Stage01MapValidator
{
    private const string GameplayScenePath = "Assets/Sandbox/Scenes/Gameplay.unity";

    [MenuItem("Peak Plunder/Stage01/Validate Gameplay Scene")]
    public static bool ValidateGameplayScene()
    {
        if (EditorSceneManager.GetActiveScene().path != GameplayScenePath)
            EditorSceneManager.OpenScene(GameplayScenePath, OpenSceneMode.Single);

        var report = new ValidationReport();

        ValidateRequiredRoots(report);
        ValidateCounts(report);
        ValidateManagers(report);
        ValidateGeneratedAssets(report);

        report.Print();
        return report.IsValid;
    }

    private static void ValidateRequiredRoots(ValidationReport report)
    {
        string[] roots =
        {
            "GameManager",
            "World",
            "GrappableRocks",
            "IcePatches",
            "Checkpoints",
            "RouteGates",
            "RelicSpawnPoints",
            "PlayerSpawnPoints",
            "HazardSpawnPoints"
        };

        foreach (string root in roots)
            report.Require(GameObject.Find(root) != null, $"Hierarchy root exists: {root}");

        string[] zones =
        {
            "Basecamp",
            "Zone1_Forest",
            "Zone2_RockySlope",
            "Zone3_CliffWall",
            "Zone4_TempleRuins",
            "Zone5_IceWall",
            "Zone6_Summit"
        };

        foreach (string zone in zones)
            report.Require(GameObject.Find(zone) != null, $"Zone marker exists: {zone}");
    }

    private static void ValidateCounts(ValidationReport report)
    {
        report.Require(CountChildren("GrappableRocks") >= 50, "GrappableRocks has at least 50 rocks");
        report.Require(CountDescendantsWithNamePrefix("Zone1_Forest", "Tree_Z1_") >= 20, "Zone1 has at least 20 trees");
        report.Require(Object.FindObjectsByType<IcePatch>(FindObjectsSortMode.None).Length >= 12, "IcePatch count is at least 12");
        report.Require(Object.FindObjectsByType<RouteGate>(FindObjectsSortMode.None).Length >= 4, "RouteGate count is at least 4");
        report.Require(Object.FindObjectsByType<ReviveShrine>(FindObjectsSortMode.None).Length >= 6, "ReviveShrine count is at least 6");
        report.Require(Object.FindObjectsByType<ZoneCheckpoint>(FindObjectsSortMode.None).Length >= 5, "ZoneCheckpoint count is at least 5");
        report.Require(GameObject.Find("SummitGoal")?.GetComponent<SummitGoalTrigger>() != null, "SummitGoalTrigger exists");

        var spawnPoints = Object.FindObjectsByType<SpawnPoint>(FindObjectsSortMode.None);
        report.Require(spawnPoints.Count(sp => sp.Layer == SpawnLayer.Relic) == 9, "Relic SpawnPoint count is 9");
        report.Require(spawnPoints.Count(sp => sp.Layer == SpawnLayer.Hazard) == 9, "Hazard SpawnPoint count is 9");
        report.Require(spawnPoints.Count(sp => sp.Layer == SpawnLayer.Item) == 5, "Item SpawnPoint count is 5");
    }

    private static void ValidateManagers(ValidationReport report)
    {
        var gameManager = GameObject.Find("GameManager");
        report.Require(gameManager != null, "GameManager exists");
        if (gameManager == null) return;

        report.Require(gameManager.GetComponent<SpawnManager>() != null, "GameManager has SpawnManager");
        report.Require(gameManager.GetComponent<ExpeditionManager>() != null, "GameManager has ExpeditionManager");
        report.Require(gameManager.GetComponent<ScoreTracker>() != null, "GameManager has ScoreTracker");
        report.Require(gameManager.GetComponent<PeakPlunder.Audio.AudioManager>() != null, "GameManager has AudioManager");

        var returnPoint = GameObject.Find("ReturnPoint");
        report.Require(returnPoint?.GetComponent<ReturnZone>() != null, "ReturnPoint has ReturnZone");
        report.Require(returnPoint?.GetComponent<Unity.Netcode.NetworkObject>() != null, "ReturnPoint has NetworkObject");
    }

    private static void ValidateGeneratedAssets(ValidationReport report)
    {
        string[] assetPaths =
        {
            "Assets/Sandbox/Prefabs/Hazards/Stage01_RockfallTrigger.prefab",
            "Assets/Sandbox/Prefabs/Hazards/Stage01_CollapsiblePlatform.prefab",
            "Assets/Sandbox/Prefabs/Hazards/Stage01_TempleTrap.prefab",
            "Assets/Sandbox/Prefabs/Items/Stage01_FieldSupply.prefab",
            "Assets/Sandbox/Terrain/MountainTerrainData.asset"
        };

        foreach (string path in assetPaths)
            report.Require(AssetDatabase.LoadAssetAtPath<Object>(path) != null, $"Generated asset exists: {path}");
    }

    private static int CountChildren(string rootName)
    {
        var root = GameObject.Find(rootName);
        return root != null ? root.transform.childCount : 0;
    }

    private static int CountDescendantsWithNamePrefix(string rootName, string prefix)
    {
        var root = GameObject.Find(rootName);
        if (root == null) return 0;

        int count = 0;
        foreach (Transform child in root.GetComponentsInChildren<Transform>(true))
        {
            if (child.name.StartsWith(prefix))
                count++;
        }

        return count;
    }

    private sealed class ValidationReport
    {
        private readonly List<string> _passed = new();
        private readonly List<string> _failed = new();

        public bool IsValid => _failed.Count == 0;

        public void Require(bool condition, string message)
        {
            if (condition) _passed.Add(message);
            else _failed.Add(message);
        }

        public void Print()
        {
            foreach (string message in _passed)
                Debug.Log($"[Stage01 Validate] PASS: {message}");

            foreach (string message in _failed)
                Debug.LogError($"[Stage01 Validate] FAIL: {message}");

            if (IsValid)
                Debug.Log($"[Stage01 Validate] OK ({_passed.Count} checks)");
            else
                Debug.LogError($"[Stage01 Validate] FAILED ({_failed.Count} failed / {_passed.Count} passed)");
        }
    }
}
#endif
